version: x.x.{build}
skip_commits:
  files:
    - README.md
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  verbosity: minimal
before_build:
- cmd: >-
    set "BUILD_VERSION=%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,8%"

    set "BUILD_VERSION_COMMA_SEP=%APPVEYOR_BUILD_VERSION:.=,%"

    set "BUILD_ZIPFILE=%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_v%BUILD_VERSION%_%PLATFORM%.zip"

after_build:
- cmd: >-
    unix2dos "%APPVEYOR_BUILD_FOLDER%\betterbns.ini"

    copy /Y "%APPVEYOR_BUILD_FOLDER%\betterbns.ini" "%APPVEYOR_BUILD_FOLDER%\bin\NCWest\NCLauncher\"

    cd "%APPVEYOR_BUILD_FOLDER%\bin"

    7z a "%BUILD_ZIPFILE%" *

artifacts:
- path: '*.zip'
